base_par <- function(...) modifyList(modifyList(DEFAULTS, list(Wprime = 20000)), list(...))
test_that("fit_recovery returns in-bounds params and converges", {
  trace <- rep(c(rep(400,20), rep(120,40)), 6)
  known <- base_par(fP = 0.30, tauP = 30, tauG = 300)
  marks <- c(which.min(simulate_tanks(trace, 250, known)$total), length(trace))
  r <- fit_recovery(trace, 250, base_par(), marks, submax = FALSE)
  expect_gte(r$fP, 0.10); expect_lte(r$fP, 0.60)
  expect_gte(r$tauP, 5);  expect_lte(r$tauP, 120)
  expect_gte(r$tauG, 60); expect_lte(r$tauG, 1800)
  expect_equal(r$conv, 0)
  expect_true(is.finite(r$obj))
})
test_that("submax path flags submax and changes the objective", {
  trace <- rep(c(rep(350,20), rep(120,40)), 5)
  r_max <- fit_recovery(trace, 250, base_par(), marks = length(trace), submax = FALSE)
  r_sub <- fit_recovery(trace, 250, base_par(), marks = integer(0), submax = TRUE)
  expect_true(r_sub$submax)
  expect_false(isTRUE(all.equal(r_max$obj, r_sub$obj)))
})
